### ISSUE TITLE
self hosted server - socket hang up

### ISSUE THREAD

**Issue by maciej-blyng** [defunctzombie/localtunnel-server#129]
The following exception is thrown at Client.js

   ```
     clientReq.once('error', (err) => {
            // TODO(roman): if headers not sent - respond with gateway unavailable
            console.err(err);
        });
```

```
"Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)"
```

Any thoughts on why would I get that.

Only replaced the debug logger with winston logger. Other than that straight from master.

**Comment by brbrr** [comment]
I experiencing a similar issue. Have you figured the problem?
